//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubActionsVS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubActionsVS.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Secret.
        /// </summary>
        public static string ADD_SECRET {
            get {
                return ResourceManager.GetString("ADD_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Run.
        /// </summary>
        public static string CANCEL_RUN {
            get {
                return ResourceManager.GetString("CANCEL_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this secret?.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string CONFIRM_DELETE_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Secret.
        /// </summary>
        public static string DELETE_SECRET {
            get {
                return ResourceManager.GetString("DELETE_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Secret.
        /// </summary>
        public static string EDIT_SECRET {
            get {
                return ResourceManager.GetString("EDIT_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo found, but not a github.com.
        /// </summary>
        public static string GIT_NOT_GITHUB {
            get {
                return ResourceManager.GetString("GIT_NOT_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Branch.
        /// </summary>
        public static string HEADER_CURRENT_BRANCH {
            get {
                return ResourceManager.GetString("HEADER_CURRENT_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        public static string HEADER_ENVIRONMENTS {
            get {
                return ResourceManager.GetString("HEADER_ENVIRONMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Secrets.
        /// </summary>
        public static string HEADER_REPO_SECRETS {
            get {
                return ResourceManager.GetString("HEADER_REPO_SECRETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        public static string HEADER_SECRETS {
            get {
                return ResourceManager.GetString("HEADER_SECRETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string HEADER_SETTINGS {
            get {
                return ResourceManager.GetString("HEADER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string HEADER_WORKFLOWS {
            get {
                return ResourceManager.GetString("HEADER_WORKFLOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient permissions to retrieve Secrets.
        /// </summary>
        public static string INSUFFICIENT_SECRET_PERMS {
            get {
                return ResourceManager.GetString("INSUFFICIENT_SECRET_PERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret:.
        /// </summary>
        public static string LABEL_SECRET {
            get {
                return ResourceManager.GetString("LABEL_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No environments defined.
        /// </summary>
        public static string NO_ENV {
            get {
                return ResourceManager.GetString("NO_ENV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GitHub repositories found. Please open a folder that contains a GitHub repository..
        /// </summary>
        public static string NO_GIT_REPO {
            get {
                return ResourceManager.GetString("NO_GIT_REPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project or solution loaded.
        /// </summary>
        public static string NO_PROJ_LOADED {
            get {
                return ResourceManager.GetString("NO_PROJ_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository secrets defined.
        /// </summary>
        public static string NO_REPO_SECRETS {
            get {
                return ResourceManager.GetString("NO_REPO_SECRETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workflow runs found for query.
        /// </summary>
        public static string NO_WORKFLOW_RUNS {
            get {
                return ResourceManager.GetString("NO_WORKFLOW_RUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Workflow.
        /// </summary>
        public static string RUN_WORKFLOW {
            get {
                return ResourceManager.GetString("RUN_WORKFLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string TRIGGERED_BY {
            get {
                return ResourceManager.GetString("TRIGGERED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggered via.
        /// </summary>
        public static string TRIGGERED_VIA {
            get {
                return ResourceManager.GetString("TRIGGERED_VIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        public static string VIEW_LOG {
            get {
                return ResourceManager.GetString("VIEW_LOG", resourceCulture);
            }
        }
    }
}
