// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHubActionsVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "TimHeuer.GitHubActions";
        public const string Name = "GitHub Actions";
        public const string Description = @"A window that provides a view of GitHub Actions for the current repo of the opened solution in Visual StudioA ";
        public const string Language = "en-US";
        public const string Version = "0.0.1";
        public const string Author = "Tim Heuer";
        public const string Tags = "github,actions,workflow,devops,dotnet";
    }
}
