// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitHubActionsVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitHubActionsVSString = "39792190-7ea1-477e-8f95-28a1132e1fc9";
        public static Guid GitHubActionsVS = new Guid(GitHubActionsVSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x0001;
        public const int ActionsCommand = 0x0100;
        public const int TWindowToolbar = 0x1000;
        public const int TWindowToolbarGroup = 0x1050;
        public const int RefreshRepoCommand = 0x0111;
        public const int GotoRepoCommand = 0x0112;
        public const int OpenSettingsCommand = 0x0113;
        public const int ReportFeedbackCommand = 0x0114;
    }
}